ROFL_CACHE = "rofl_filecache"
ROFL_CACHE_LAYER = "rofl_filecache_layer"
ROFL_FLIPBOOK = "rofl_flipbook"
ROFL_RENDER = "rofl_render"
ROFL_WEDGER = "rofl_wedger"
ROFL_DAILLIES = "rofl_daillies"
ROFL_SEQUENCER = "rofl_sequencer"